---
- name: get composer-installer signature
  uri:
    url: https://composer.github.io/installer.sig
    return_content: true
  register: signature

- name: download composer-installer
  get_url:
    url: https://getcomposer.org/installer
    checksum: sha384:{{ signature.content }}
    dest: /tmp/composer-setup.php

- name: install composer globally
  command: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- name: remove composer-installer
  file:
    path: /tmp/composer-setup.php
    state: absent
