---
 - hosts: webservers
   become: yes
#   user: vagrant

   user: root
   roles:
    - prepare
    - git
    - nginx
    - php
    - redis
    - supervisor
    - webserver
    - distribution
    - reload