---
- name: determine if code distributed
  stat:
    path: "{{ new_application_path }}"
  register: code_stat
- name: determine if code distributed
  shell: "mkdir -p {{ new_application_path }}"
  when: not code_stat.stat.exists
  become: true
  become_user: "{{ application_user }}"
- name: distribute code with git
  git:
   accept_hostkey=yes update=yes force=yes  dest={{ new_application_path }}   repo={{ repository }} update=yes version=master
  when: not code_stat.stat.exists
  become: true
  become_user: "{{ application_user }}"
#  git:
#    repo: {{ repository }}
#    dest: "{{ new_application_path }}"
#    version: master
#    accept_hostkey: true
- name: chmod storage
  shell: chmod -R 777 storage
  args:
    chdir: "{{ new_application_path }}"
  when: not code_stat.stat.exists
  sudo: true
- name: composer install
  shell: composer install
  args:
    chdir: "{{ new_application_path }}"
  when: not code_stat.stat.exists
  become: true
  become_user: "{{ application_user }}"

- name: setup application env file
  template:
    src: templates/env.j2
    dest: "{{ new_application_path }}/.env"
  become: true
  become_user: "{{ application_user }}"

- name: run migrations
  shell: php artisan migrate --force
  args:
    chdir: "{{ new_application_path }}"
  become: true
  become_user: "{{ application_user }}"
  when: jobserver

- name: link code to current application version
  file:
    path: "{{ application_path }}"
    src: "{{ new_application_path }}"
    state: link
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
  register: release_stat
